- benchmarks/time_cosmology.py
Since we've had actual performance related issues raised for the cosmology
package, it seems like a good thing to have some benchmarks.
I haven't actually been able to run these -- something in the setup requires
anaconda, which I don't use.  But the class compiles and the methods run
without complaint, so it should be okay.
> Add basic cosmology timing tests

- asv.conf.json
I propose to edit `asv.conf.json`  to run the benchmarks against Python 3.6 instead of 3.4.
Motivation:
* Python 3 users tend to be on the latest version;
* I find the benchmarks to be significantly faster on 3.6 compared to 3.4, cf the graph below which I tweeted here: https://twitter.com/GeertHub/status/817857735484198912
> Run the benchmarks against 3.6 instead of 3.4

- benchmarks/cosmology.py
The no-radiation case (Tcmb0=0) for distance and age calculations have optimizations available and some implemented.
Add these to the FlatLambdaCDM, LambdaCDM benchmarks to track current state and future progress.
> Add no-radiation cases to FlatLambdaCDM, LambdaCDM benchmarks

- benchmarks/io_ascii/ipac.py
I haven't identified just where the regression occurred, but @hamogu heavily refactored how io.ascii classes are set up and I suspect that might be what happened.  The point is that (at least for IPAC) you can't use the bare classes in isolation, they are really more integrated.
Anyway, I made it work.
Fixes #17
> Fix io.ascii IPAC benchmarks

- .gitignore
Is this a legit fix? I don't know. I just don't want `git` to complain about untracked directory when I run stuff in the `master` clone. 😬
> Ignore results since they are in separate branch

- benchmarks/stats/sigma_clipping.py
Followup to #55.
CC: @astrofrog
> Use smaller array to prevent timeout

- asv.conf.json
Astropy is not compatible with numpy 1.11 any more, so I'm removing it from the default config so people try to run the benchmarks as is don't run into errors.
> Removing numpy 1.11 from the default conf

- README.rst
This cleans up and adds the full instructions to the README file. I originally thought I'd add it to the astropy dev docs but that actually doesn't seem right because we should just keep the instructions close to the benchmarks.
[Preview here](https://github.com/astropy/astropy-benchmarks/blob/758dcab794907951f399009169a65f07cff54240/README.rst)
> Added detailed instructions to README.rst

- benchmarks/coordinates.py
This is a complement to astropy/astropy#7924 that adds benchmarks relevant to the speed improvements in that PR.
> Add benchmarks for attaching differentials to representations

- benchmarks/io_fits.py
Closes #76, and also ref https://github.com/astropy/astropy/pull/8502
I ran this locally to compare https://github.com/astropy/astropy/pull/8502 with v3.0.2 (so the comparison also includes changes from https://github.com/astropy/astropy/pull/8428, it is just to check that it is working correclty):
```
(py37) ❯ asv compare 275807902 0608e7a57
All benchmarks:
before           after         ratio
[27580790]       [0608e7a5]
728±1ms        741±0.3ms     1.02  io_fits.FITSBinTableHDU.time_from_columns_bytes
33.2±1ms         21.1±0ms    ~0.63  io_fits.FITSHDUList.time_getheader
-         1.59±0s        157±0.1ms     0.10  io_fits.FITSHDUList.time_getheader_ext50
-         3.15±0s        256±0.6ms     0.08  io_fits.FITSHDUList.time_len
-      21.6±0.2ms      18.4±0.04ms     0.85 …
```
> Add fits benchmarks

- asv.conf.json
Alternative to https://github.com/astropy/astropy-benchmarks/pull/83 - basically we need to update the version of numpy to at least 1.16 since that's what astropy now requires. I updated to the most recent supported versions of several dependencies so that this lasts a little while.
> Updated version of dependencies used in environment

- benchmarks/imports.py
Fix #20 
Using example from airspeed-velocity/asv#832
**NOTE from local testing without asv**
Subsequent import of `astropy` even after deleting it from Python namespace does not take as long as the initial import. 
```python
In [1]: %time import astropy                                                    
CPU times: user 455 ms, sys: 985 ms, total: 1.44 s
Wall time: 193 ms
In [2]: %time import astropy                                                    
CPU times: user 2 µs, sys: 2 µs, total: 4 µs
Wall time: 6.2 µs
In [3]: import sys                                                              
In [4]: del sys.modules['astropy']                                              
In [5]: %time import astropy                                                    
CPU times: user 1.78 ms, sys: 871 …
```
> Add raw import benchmark for astropy

- benchmarks/io_fits.py
@saimn - for info, the setup function previously took 67 seconds on my benchmark machine which is why there was no data. With these changes, the benchmarks work fine.
> Reduce time for FITS HDUList benchmarks

- asv.conf.json
- benchmarks/imports.py
* Add `pyyaml` to hopefully fix https://www.astropy.org/astropy-benchmarks/#imports.timeraw_import_astropy_io_misc_yaml
* Remove `timeraw_import_astropy_tests_helper` because it produces empty result, and probably overkill to begin with.
> Add pyyaml and remove helper import

- benchmarks/table.py
Fix #99 
I only ported over the cells with `timeit` in https://gist.github.com/taldcroft/2fa546ecb13ebe4a7ebc33ffa5dbb016 . cc @mhvk 
The `setup` has a lot of copies of large arrays. If this will present memory problem, please let me know how to mitigate the problem. Thanks!
💯
> ENH: Add more table init benchmarks from taldcroft

- README.rst
- cron.sh
This PR attempts to replace all mention of `master` to `main` in this repository. This should be reviewed and merged right after the maintainer has renamed the default branch.
This is part of #103
> MNT: Replace master with main

- README.rst
Following the removal of `asv dev` upstream. Xrefs
- https://github.com/airspeed-velocity/asv/issues/1200
- https://github.com/airspeed-velocity/asv/pull/1371
> DOC: drop asv dev command alias from docs

- .github/workflows/main.yml
- tox.ini
We should make sure that there are no syntax or code issues and that the benchmarks run with the latest version of astropy, otherwise we risk introducing broken benchmarks here and breaking the astropy CI subsequently.
> Run benchmarks in quick mode in CI

- .github/workflows/main.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
> MNT: Use hash for Action workflow versions and update if needed

- benchmarks/convolve.py
This came up in https://github.com/astropy/astropy/pull/17494 where we want to remove the original (and unused) benchmark code from the core library. As far as I can tell most of the code was already ported in #73, with the difference that `convolve_fft` isn't ported yet.
> Add a benchmark for `convolve_fft`

- benchmarks/timeseries.py
Would have caught the performance regression in v7.1.0 ( https://github.com/astropy/astropy/issues/18176 ), being fixed by PR https://github.com/astropy/astropy/pull/18188 .
The benchmark results on my machine
| `aggregate_func` | v7.1.0     | with astropy PR #18188 |
| ---------------- | ---------- | ---------------------- |
| `None`           | 9.49±0.2ms | 9.79±0.3ms             |
| `np.nanmean`     | 186±20ms   | 119±3ms                |
@mvhk @pllim
> Benchmarks for timeseries `aggregate_downsample()`
