astropy/astropy-benchmarks

benchmarks/time_quantity.py
Adds some benchmarks, also slightly rewrites others, to ensure we are timing `Quantity`, not numpy.
=> Add some quantity initialization and computation benchmarks.

.travis.yml, asv.conf.json
This makes it easier to run the tests for a local clone
=> Explicitly set DVCS to git and added example local clone URL

benchmarks/time_coordinates.py, benchmarks/time_fits.py
I renamed the existing tests in coordinates that I modified to make sure they don't count as the same test as before (in case performance changes)
=> Expand coordinates and add new FITS benchmarks

benchmarks/units.py
Fixes https://github.com/astropy/astropy-benchmarks/issues/26
=> Added a benchmark for unit composition with a complex unit

benchmarks/coordinates.py
=> Added benchmarks for Angle.__repr__, Angle.__str__ and Angle._repr_latex_

README.rst
Resolves #46
Signed-off-by: James Noss <jnoss@stsci.edu>
=> Fix broken ASV link in README.rst

benchmarks/table.py
Fix #48 
xref: astropy/astropy#7399, astropy/astropy#7422, astropy/astropy#7423
=> Add benchmark for masked column

benchmarks/units.py
Fix #53. xref astropy/astropy#7546 and astropy/astropy#7549
=> Add benchmarks from unyt paper (Goldbaum 2018)

benchmarks/stats/sigma_clipping.py
=> Smaller array for sigma clipping 3D test

README.rst
So it's easier to find the detailed docs.
=> Adding a link for the google docs

benchmarks/coordinates.py
What it says on the label!
This is a companion to astropy/astropy#7922
=> Add benchmark for concatenate function

benchmarks/coordinates.py
This tests different paths through the SkyCoord initializer in a bit more of a controlled manner.
=> More SkyCoord benchmarks

benchmarks/convolve.py
Before merging, I need to make sure they won't be too slow to run on the physical asv machine.
=> Added benchmarks for astropy.convolve

.travis.yml, benchmarks/coordinates.py, benchmarks/stats/sigma_clipping.py
This is an attempt to debug the existing CI issues and also to make sure that the benchmarks can be run with older versions of astropy.
=> Improve continuous integration

benchmarks/imports.py
=> Add subpackage import benchmarks

benchmarks/io_ascii/table.py
Fix #87 
Many thanks to @pv for the help!
Bonus: PEP 8
cc @mhvk (somehow unable to add you as reviewer)
=> Fix mem profiling error for ASCII Table

.travis.yml, asv.conf.json, benchmarks/modeling/compound.py, benchmarks/modeling/model.py
Why is everything breaking?
Not sure why but airspeed-velocity/asv#928 . 🤷 
Also needed the patch from #95 because `np.linspace` complains about exponent not being an int. Close #95 (cc @hamogu)
Fix #94
=> TST: Fix CI

benchmarks/table.py
Many thanks to @mcara and @bhayden53 from astropy/astropy#10548 for identifying this.
cc @mhvk
=> Add benchmark from astropy Issue 10548

asv.conf.json, benchmarks/environment.yml, benchmarks/modeling/fitting.py
This PR:
- updates the configuration to use the `main` branch
- uses Python 3.11 by default
- adds model fitting benchmarks from @WilliamJamieson
=> updates from fork

asv.conf.json
=> Use HTTPS on asv.conf.json
